'use strict';
// Todas las variables que se van a usar en varios archivos
export var cookies = document.cookie.split('; ');

export var descripcionAcertijos = ["Cuanto más quites de él, más grande se vuelve",
    "Amarillo por dentro, verde por fuera. Si quieres que te lo diga, espera",
    "Si me nombras, eliminas mi existencia",
    "Vuela sin alas, llora sin ojos",
    "Ligero como el viento, lo puedes ver, pero no lo puedes tocar"];

export var titulosAlternativosHistorias = ["La Puerta Arañada y la Evolución de un Vínculo", "Enigma nocturno: El armario que guarda más que ropa", "El legado fotográfico de Michael", "El misterioso poder del pozo: Un relato retorcido de amor y desapariciones", "El eco inquietante de las 10:30 de la noche"];

export var descripcionHistorias = [
    "De pequeño me hacia gracia escuchar que mi gato arañara la puerta de mi habitación para que le dejara entrar, cada noche sigue ocurriendo pero es extraño que me siga pareciendo entrañable ahora que vivo solo.",
    "Amanda estaba sentada en su habitación, escuchando música con los cascos mientras hacía los deberes, tal como le había pedido su madre antes de ir a comer. Estaba a punto de terminar cuando su madre, desde abajo de las escaleras, le gritó que si ya había terminado, podía bajar porque la cena ya estaba lista. Aunque le quedaba un poco por terminar pensó que lo terminaría después. Bajó rápidamente las escaleras,pero justo antes de entrar en la cocina alguien le agarró por detrás, tapándole la boca y la metieron en un armario. Estaba asustadísima, pero el miedo desapareció al instante en el que se dió cuenta que era su madre, demacrada, más envejecida y con una mirada más asustada que la suya propia. La madré miro a Amanda y le dijo: 'No grites, yo también lo he escuchado'",
    "Fue como ocurren la mayoría de accidentes en la carretera, injustos y repentinos. Michael era nuestro amigo, nos conocimos todos cuando éramos pequeños en el barrio, y ahora parece increíble que estemos en su entierro. Sus padres no querían tirar sus cosas a la basura, nos dijeron que, si queríamos, podíamos ir a recogerlas aunque sea como recuerdo, supongo que de alguna manera de esta forma sería más reconfortante para ellos. Decidimos ir y vimos que su habitación estaba hecha un desastre, aunque era de esperar, ya que Michael no destacaba por ser ordenado. Por lo que vimos en su habitación, sí que parecía gustarle mucho la fotografía, tenía albumes llenos de fotos de todo tipo. Nos quedamos un rato mirándolas hasta que una foto en particular provocó un silencio repentino. Era una foto en el que la cámara apuntaba de cara al espejo de un baño, reflejando solamente el cuarto de baño y una cámara",
    "De pequeño, le molestaba mucho el llanto de su hermano pequeño por lo que impulsivamente lo mató y tiró su cuerpo en el pozo que tenía cerca de su casa. Al día siguiente, sin saber por qué, el cuerpo había desaparecido. Pensando que fue obra del destino decidío que su hermano no sería su última víctima. En la adolescencia se peleó con su mejor amigo por algo que no era tan importante para acordarse pero parecía sufiente como para matarlo y tirar su cuerpo al pozo. De nuevo, el día siguiente el cadáver ya no estaba. Cinco años después, mató a su primera novia, aunque fuese accidentalmente, no pudo negar que no le acabó gustando el haberlo hecho. Esperando que el pozo hiciera su magia, lanzó el cuerpo y a la mañana siguiente desapareció. Mató también a su jefe porque, al parecer, no se le daba bien aceptar órdenes, lo tiró al pozo y nunca más se supo del cadáver. Ya cerca de los cuarenta años, encontró el valor que nunca había tenido hasta en ese momento y mató a su propia madre, matarla había sido tan especial e íntimo como siempre se había imaginado. Tiró el cadáver al pozo y al día siguiente, sorprendentemente, aún seguía allí. Es una historia retorcida de amor cuando te das cuenta",
    "Un día normal y corriente estaba en mi habitación, haciendo lo que siempre hago. Cuando llega la hora de poner el despertador para el día siguiente, me fijo en la hora, como siempre hago para saber cuantas horas tendré de sueño, y veo que son las 10:30 de la noche. Contento, veo que podré dormir lo deseado y me tumbo en la cama. De repente escucho golpes en mi armario, decido ignorarlo pensando que era el viento moviendo las puertas y me vuelvo a dormir. Los golpes se volvieron más y más seguidos por lo que me despierto y decido abrir el armario para ver qué sucedía. Sin esperarmelo, siento un dolor punzante en el pecho y de reojo veo tras abrir el armario un ser humanoide mucho más alto que yo, con su mano puntiaguda atravesandóme el pecho, poco tiempo después pierdo el conocimiento. De golpe me despierto,suspirando fuertemente pero al mismo tiempo tranquilizado que lo sucedido anteriormente fuese una pesadilla, cojo el teléfono móvil y se me queda la mente en blanco al escuchar los mismos golpecitos que escuchaba en la pesadilla y en cuanto veo que la hora es 10:30 de la noche, empiezo a sudar frío."];